apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        denglanlan/jenkins-teeest: true
        denglanlan/python-http: true
        denglanlan/python-http-test01: true
        denglanlan/test-project: true
        denglanlan/test-project-jenkins: true
        denglanlan/text12: true
        keefans/k3s-jx3-sky: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        denglanlan/jenkins-teeest: merge
        denglanlan/python-http: merge
        denglanlan/python-http-test01: merge
        denglanlan/test-project: merge
        denglanlan/test-project-jenkins: merge
        denglanlan/text12: merge
        keefans/k3s-jx3-sky: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - keefans/k3s-jx3-sky
        - denglanlan/jenkins-teeest
        - denglanlan/python-http-test01
        - denglanlan/python-http
        - denglanlan/test-project-jenkins
        - denglanlan/test-project
        - denglanlan/text12
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - keefans/k3s-jx3-sky
        - denglanlan/jenkins-teeest
        - denglanlan/python-http-test01
        - denglanlan/python-http
        - denglanlan/test-project-jenkins
        - denglanlan/test-project
        - denglanlan/text12
      target_url: http://dashboard-jx.jx3.sky-cloud.net
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
